// Generates supabase/seed/seed.sql from src/data/seed.json + default pages/menus/modules.
// Run: node scripts/seed-to-sql.ts   (after node scripts/build-seed.ts)
// The seed contains PUBLIC SOURCE METADATA ONLY — no private questions, no fake answers.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import type { SeedData } from '../src/shared/types.ts';
import { DEFAULT_HOME, DEFAULT_MENUS, DEFAULT_PAGES } from '../src/shared/defaults.ts';
import { MODULES } from '../src/modules/manifest.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const seed: SeedData = JSON.parse(readFileSync(resolve(root, 'src/data/seed.json'), 'utf8'));

const q = (v: unknown): string => {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};
const uuid = (key: string) => {
  const h = createHash('sha1').update('or-hameir:' + key).digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-5${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`;
};
const rows = (table: string, cols: string[], values: unknown[][], conflict = 'id') =>
  values.length
    ? `insert into public.${table} (${cols.join(', ')}) values\n${values.map((r) => `  (${r.map(q).join(', ')})`).join(',\n')}\non conflict ${conflict === 'series_id, content_id' ? '(series_id, content_id) ' : ''}do nothing;\n`
    : '';

const out: string[] = [
  '-- GENERATED by scripts/seed-to-sql.ts — do not edit by hand.',
  `-- Source: ${seed.sourceFile}; audit: ${JSON.stringify(seed.audit).replace(/\n/g, ' ')}`,
  '-- Public source metadata only. Insert-only and idempotent: ON CONFLICT DO NOTHING on every unique key,',
  '-- so a re-run never duplicates rows and never overwrites rows that already exist (including CMS edits).',
  'begin;',
  // Marks this transaction as the service role so workflow triggers accept published seed rows.
  `select set_config('request.jwt.claims', '{"role":"service_role"}', true);`,
];

out.push(rows('source_archives', ['id', 'name', 'material', 'url', 'verification', 'note'],
  seed.archives.map((a) => [a.id, a.name, a.material, a.url, a.verification, a.note])));

out.push(rows('topics', ['id', 'slug', 'name', 'description', 'sort', 'auto', 'status'],
  seed.topics.map((t) => [t.id, t.slug, t.name, t.description, t.sort, t.auto ?? false, t.status])));

out.push(rows('content_items',
  ['id', 'slug', 'type', 'title', 'summary', 'body', 'speaker', 'attribution_status', 'attribution_note', 'event_date', 'event_date_text',
   'source_published_date', 'duration_seconds', 'duration_text', 'status', 'published_at', 'featured', 'verification', 'provenance',
   'duplicate_group', 'catalog_order'],
  seed.content.map((c) => [c.id, c.slug, c.type, c.title, c.summary, c.body, c.speaker, c.attributionStatus, c.attributionNote, c.eventDate,
    c.eventDateText, c.sourcePublishedDate, c.durationSeconds, c.durationText, c.status, c.publishedAt, c.featured, c.verification,
    c.provenance, c.duplicateGroup, c.catalogOrder])));

out.push(rows('book_details', ['content_id', 'author_text', 'editor_text', 'publisher', 'authored_by_rabbi', 'cover_path', 'pdf_access', 'located_status'],
  seed.content.filter((c) => c.bookDetails).map((c) => {
    const b = c.bookDetails!;
    return [c.id, b.authorText, b.editorText, b.publisher, b.authoredByRabbi, b.coverPath, b.pdfAccess, b.locatedStatus];
  }), 'content_id'));

out.push(rows('media_sources',
  ['id', 'content_id', 'provider', 'provider_id', 'url', 'canonical_url', 'delivery_mode', 'kind', 'mime', 'rights_status', 'rights_evidence',
   'embed_status', 'is_primary'],
  seed.content.flatMap((c) => c.sources.map((s) => [s.id, s.contentId, s.provider, s.providerId, s.url, s.canonicalUrl, s.deliveryMode,
    s.kind, s.mime, s.rightsStatus, s.rightsEvidence, s.embedStatus, s.isPrimary]))));

out.push(rows('content_topics', ['content_id', 'topic_id', 'auto'],
  seed.content.flatMap((c) => c.topicIds.map((t) => [c.id, t, true])), 'content_id, topic_id'));

out.push(rows('series', ['id', 'slug', 'title', 'description', 'kind', 'source_url', 'status', 'sort'],
  seed.series.map((s) => [s.id, s.slug, s.title, s.description, s.kind, s.sourceUrl, s.status, s.sort])));
out.push(rows('series_items', ['series_id', 'content_id', 'position'],
  seed.series.flatMap((s) => s.items.map((cid, i) => [s.id, cid, i])), 'series_id, content_id'));

out.push(rows('institutions', ['id', 'slug', 'name', 'description', 'source_urls', 'status'],
  seed.institutions.map((i) => [i.id, i.slug, i.name, i.description, i.sourceUrls, i.status])));
out.push(rows('events', ['id', 'slug', 'institution_id', 'title', 'event_date', 'date_text', 'summary', 'source_urls', 'status'],
  seed.events.map((e) => [e.id, e.slug, e.institutionId, e.title, e.eventDate, e.dateText, e.summary, e.sourceUrls, e.status])));

out.push(rows('pages', ['id', 'slug', 'title', 'description', 'blocks', 'status'],
  DEFAULT_PAGES.map((p) => [uuid('page:' + p.slug), p.slug, p.title, p.description, p.blocks, p.status])));
out.push(rows('menus', ['id', 'location', 'items'], DEFAULT_MENUS.map((m) => [uuid('menu:' + m.location), m.location, m.items])));
out.push(rows('homepage_sections', ['id', 'kind', 'title', 'enabled', 'position', 'config'],
  DEFAULT_HOME.map((h) => [uuid('home:' + h.kind), h.kind, h.title, h.enabled, h.position, h.config])));
out.push(rows('modules', ['id', 'enabled', 'settings'],
  MODULES.map((m) => [m.id, m.enabledByDefault, Object.fromEntries(m.settings.map((s) => [s.key, s.default]))])));

out.push('commit;\n');
mkdirSync(resolve(root, 'supabase/seed'), { recursive: true });
writeFileSync(resolve(root, 'supabase/seed/seed.sql'), out.join('\n'));
console.log(`seed.sql: ${seed.content.length} content items, ${seed.content.reduce((n, c) => n + c.sources.length, 0)} sources`);
